### ISSUE TITLE
Chrome Web Store shows warning

### ISSUE THREAD

**Issue by objectiveryan** [coedit/gcal-rainbow-surf#12]
https://chromewebstore.google.com/detail/rainbowsurf-for-google-ca/bdamkdibjdpgnpfpkbelkdngdcbbaeog says "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions."

Why is that? Is it the Manifest V3 migration?

**Comment by ezdub** [comment]
Yes, because MV3 phase-out. Thank you for bringing attention to this. I'm traveling now but will submit an updated version to the stoor soon, before the actual MV3 phase-out on chrome-stable. Or you can test & submit a PR to increase velocity. 
Thanks again!

**Comment by ezdub** [comment]
Unfortunately, this issue slipped off my radar for a while, but the updates are completed and currently under review in the Chrome Web Store. The warning should disappear shortly when they approve publishing the update.

**Comment by ezdub** [comment]
The resolved update is now published by Google to the Chrome Web Store. If a warning that this extension is no longer supported still appears in your web browser, please close it and reopen it. If you've removed this extension, you may reinstall it by clicking ["Add to Chrome" on the CWS listing](https://chromewebstore.google.com/detail/rainbowsurf-%E2%80%94-merge-dupli/bdamkdibjdpgnpfpkbelkdngdcbbaeog)
